# The URL the site will be built for
base_url = "https://breadcat.neocities.org"
title = "Breadcat's Oven"
description = "UwU~"
author = "Alexa"

default_language = "en"

generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
    {name = "tags", render = false}
]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
smart_punctuation = true
highlight_code = true
highlight_theme = "ayu-dark"

[extra]
# Put all your custom variables here

[languages.fr]
generate_feeds = true
taxonomies = [
    {name = "tags", render = false}
]

[translations]
home = "Home"
hosted_by = "Hosted by"
built_with = "Built with"
source_code = "Source Code"
last_update = "Last update"
toc = "Welcome ~"
the_buttons = "The Obligatory Buttons"
fedi_feed = "Fediverse Feed"
atom_feed = "Atom/RSS Feed"
jump_i18n = "Accéder à la version Française"

back = "Back"

[languages.fr.translations]
home = "Accueil"
hosted_by = "Hébergé par"
built_with = "Compilé avec"
source_code = "Code Source"
last_update = "Dernière MàJ"
toc = "Bienvenu·e ~"
the_buttons = "Les Incontournables Boutons"
fedi_feed = "Flux du Fédiverse"
atom_feed = "FLux Atom/RSS"
jump_i18n = "Jump to English version"

back = "Retour"